### ISSUE TITLE
How to input

### ISSUE THREAD

**Issue by moshem1234** [jsoslow2/Fantasy-Football-Models-Old#3]
> Insert who's been drafted thus far, and who's on your team
Where and how would I input this in?

**Comment by gatsbysghost** [comment]
[In this section](https://github.com/jsoslow2/Fantasy-Football-Models/blob/b8d3d115b5ad5a721f52ab108be440c0d3f6575f/Fantasy%20Football%20Analysis%20v2.Rmd#L1747)

**Comment by Corran9** [comment]
I'm relatively new to R. I've reviewed the code, but I still don't see where we set who has been drafted

**Comment by gatsbysghost** [comment]
In the link I posted in my last comment, you'll find the block where you can post who's been drafted.

e.g.:

draftedOverall <- c(
    'AaronRodgers',
    'DavanteAdams'
                    )

**Comment by JetJadeja** [comment]
@gatsbysghost, when I paste the names of already drafted players, nothing in actually changes in the output file. Am I missing something?

**Comment by gatsbysghost** [comment]
After you did that, did you then run the `Who's been drafted` and `OPTIMIZER ALERT WEE WOO` sections again? I've found that this generally works for me.

**Comment by JetJadeja** [comment]
Yep, just realized my problem was not running the `Who's been drafted` section yet. Appreciate your help!

**Comment by gatsbysghost** [comment]
np! R is new for me too, and the IDE model of R Studio is super unusual if you're used to most other langs :)

I think ideally what I would want to bolt onto this excellent model is something that keeps track of who is drafting who during a live draft--it can be tricky to keep track of this manually, especially if you only have ~30 seconds to run the optimizer again, make decisions, and hit the go button.

I wonder if ESPN/NFL has an API that could be exposed for this kind of thing...other than that the best option might just be a horrible python web scrape
